USE DBMS;

CREATE TABLE DEPARTMENT
(
	DEPARTMENTID INT PRIMARY KEY IDENTITY(1,1),
	DEPARTMENTNAME VARCHAR(100) NOT NULL UNIQUE,
	DEPARTMENTCODE VARCHAR(50) NOT NULL UNIQUE,
	LOCATION VARCHAR(50) NOT NULL
);

INSERT INTO DEPARTMENT VALUES
('Admin','Adm','A-Block'),
('Computer','CE','C-Block'),
('Civil','CI','G-Block'),
('Electrical','EE','E-Block'),
('Mechanical','ME','B-Block');

CREATE TABLE PERSON
(
	PERSONID INT PRIMARY KEY IDENTITY(101,1),
	PERSONNAME VARCHAR(100) NOT NULL,
	DEPARTMENTID INT FOREIGN KEY REFERENCES DEPARTMENT(DEPARTMENTID),
	SALARY DECIMAL(8,2) NOT NULL,
	JOININGDATE DATETIME NOT NULL,
	CITY VARCHAR(100) NOT NULL
);

INSERT INTO PERSON VALUES
('Rahul Tripathi',2,56000,'01-JAN-2000','Rajkot'),
('Hardik Pandya',3,18000,'25-SEP-2001','Ahmedabad'),
('Bhavin Kanani',4,25000,'14-MAY-2000','Baroda'),
('Bhoomi Vaishnav',1,39000,'08-FEB-2005','Rajkot'),
('Rohit Topiya',2,17000,'23-JUL-2001','Jamnagar'),
('Priya Menpara',NULL,9000,'18-OCT-2000','Ahmedabad'),
('Neha Sharma',2,34000,'25-DEC-2002','Rajkot'),
('Nayan Goswami',3,25000,'01-JUL-2001','Rajkot'),
('Mehul Bhundiya',4,13500,'09-JAN-2005','Baroda'),
('Mohit Maru',5,14000,'25-MAY-2000','Jamnagar');

-------------------- [ PART-A ] --------------------

-- 1. Find all persons with their department name & code.
SELECT P.PERSONNAME,D.DEPARTMENTNAME,D.DEPARTMENTCODE FROM PERSON P
INNER JOIN DEPARTMENT D
ON D.DEPARTMENTID=P.DEPARTMENTID;

-- 2. Give department wise maximum & minimum salary with department name.
SELECT D.DEPARTMENTNAME,MIN(P.SALARY) AS 'MIN SALARY',MAX(P.SALARY) AS 'MAX SALARY' FROM PERSON P
INNER JOIN DEPARTMENT D
ON D.DEPARTMENTID=P.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME;

-- 3. Find all departments whose total salary is exceeding 100000.
SELECT D.DEPARTMENTNAME,SUM(P.SALARY) AS 'SALARY' FROM DEPARTMENT D
INNER JOIN PERSON P
ON P.DEPARTMENTID=D.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME
HAVING SUM(P.SALARY)>100000;

-- 4. Retrieve person name, salary & department name who belongs to Jamnagar city.
SELECT P.PERSONNAME,P.SALARY,D.DEPARTMENTNAME FROM PERSON P
INNER JOIN DEPARTMENT D
ON D.DEPARTMENTID=P.DEPARTMENTID
WHERE P.CITY='JAMNAGAR';

-- 5. Find all persons who does not belongs to any department.
SELECT P.PERSONNAME FROM PERSON P
INNER JOIN DEPARTMENT D
ON D.DEPARTMENTID=P.DEPARTMENTID
WHERE D.DEPARTMENTNAME IS NULL;

-------------------- [ PART-B ] --------------------

-- 1. Find department wise person counts.
SELECT D.DEPARTMENTNAME,COUNT(P.PERSONID) AS 'PERSON' FROM DEPARTMENT D
INNER JOIN PERSON P 
ON P.DEPARTMENTID=D.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME;

-- 2. Find average salary of person who belongs to Ahmedabad city.
SELECT PERSONNAME,AVG(SALARY) AS 'SALARY' FROM PERSON
WHERE CITY='AHMEDABAD'
GROUP BY PERSONNAME;

-- 3. Produce Output Like: <PersonName> earns <Salary> from department <DepartmentName> monthly. (In Single Column)
SELECT CONCAT(P.PERSONNAME,' EARNS ',P.SALARY,' FROM DEPARTMENT ',D.DEPARTMENTNAME,' MONTHLY. ') AS 'PERSON DETAILS' FROM PERSON P
INNER JOIN DEPARTMENT D
ON D.DEPARTMENTID=P.DEPARTMENTID;

-- 4. List all departments who have no persons.
SELECT D.DEPARTMENTNAME FROM DEPARTMENT D
INNER JOIN PERSON P
ON P.DEPARTMENTID=D.DEPARTMENTID
WHERE P.PERSONNAME IS NULL
GROUP BY D.DEPARTMENTNAME;

-- 5. Find city & department wise total, average & maximum salaries.
SELECT P.CITY,D.DEPARTMENTNAME,AVG(P.SALARY) AS 'AVG SALARY',MAX(P.SALARY) AS 'MAX SALARY' FROM PERSON P
INNER JOIN DEPARTMENT D
ON D.DEPARTMENTID=P.DEPARTMENTID
GROUP BY P.CITY,D.DEPARTMENTNAME;

-------------------- [ PART-C ] --------------------

-- 1. Display Unique city names.
SELECT DISTINCT(CITY) FROM PERSON;

-- 2. List out department names in which more than two persons.
SELECT D.DEPARTMENTNAME,COUNT(P.PERSONID) AS 'PERSON' FROM DEPARTMENT D
INNER JOIN PERSON P
ON P.DEPARTMENTID=D.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME
HAVING COUNT(P.PERSONID)>2;

-- 3. Combine person name's first three characters with city name's last three characters in single column.
SELECT CONCAT(LEFT(PERSONNAME,3),' ',RIGHT(CITY,3)) AS 'PERSON CITY' FROM PERSON;

-- 4. Give 10% increment in Computer department employee's salary.
UPDATE PERSON SET SALARY=SALARY+SALARY*10/100 
WHERE DEPARTMENTID IN(SELECT DEPARTMENTID FROM DEPARTMENT WHERE DEPARTMENTNAME='COMPUTER');
SELECT * FROM PERSON;

-- 5. Display all the person name's who's joining dates difference with current date is more than 365 days.
SELECT PERSONNAME FROM PERSON
WHERE DATEDIFF(DAY,JOININGDATE,GETDATE())>365;